### ISSUE TITLE
Error: Protocol error (Page.enable): Target closed

### ISSUE THREAD

**Issue by sefatanam** [AjanShrestha/intelius#9]
Hey, I tried to use this project using node version 10. I install node version 10 via `nvm install 10` and it automatically download this version I mention below. Then I installed all the dependencies by `npm install` also this thing,
`Downloading Chromium r641577 - 109.8 Mb [====================] 100% 0.0s ` downloaded. Now I cant run this project it showing me this error. I also created `.env` file according the instruction that are mention in https://github.com/AjanShrestha/intelius/issues/6

```
Node Version : 10.24.1
Npm Version : 6.14.12
```

```
{ Error: Protocol error (Page.enable): Target closed.
    at Promise (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/Connection.js:182:12)
    at Function.create (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/Page.js:47:18)
    at _pagePromise._sessionFactory.then.client (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/Target.js:71:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Target.<anonymous> (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/helper.js:110:27)
    at Browser._createPageInContext (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/Browser.js:177:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Browser.<anonymous> (/home/mds/Documents/personal/intelius/node_modules/puppeteer/lib/helper.js:110:27)
    at Object.page (/home/mds/Documents/personal/intelius/src/utils/webGateway.js:21:30)
    at /home/mds/Documents/personal/intelius/src/index.js:16:37
    at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Page.enable): Target closed.' }
```

**Comment by sefatanam** [comment]
I'm going to close this issue because I thought the dashboard URL (https://iservices.intelius.com/premier/dashboard.php) does not exist anymore. If you think it should be then you can re-open this issue.

#6 Here is mentioned , `P.S. : If the website has been updated, the the scraping would not work. Also, keep in mind Intelius has anti-scraping mechanism. The code doesn't have a work around for it.`
